name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/deploy_docs.yaml
      - mkdocs.yml

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploying MkDocs documentation
        run: |
          mkdocs build
          mkdocs gh-deploy --force
